#Ean Hernandez hw5
FLAGS=-Wall -std=gnu99
CC=gcc

all : my_npipe_reader my_npipe_writer

my_npipe_reader : my_npipe_reader.o

my_npipe_writer : my_npipe_writer.o

test : t.sh
	./t

clean : 
	rm -f my_npipe_reader and my_npipe_writer *.o local_named_pipe

